
pull_request_rules:
  - name: Automatic merge of scala-steward PRs
    conditions:
      - head~=^update/
      - check-success=build-and-test
    actions:
      delete_head_branch:
        force: true
  - name: automatic merge of dependabot 🤖
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-and-test
      - base=main
    actions:
      delete_head_branch:
        force: true
  - name: Automatic merge of scala-steward PRs + automatic merge of dependabot 🤖
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from Automatic merge of scala-steward PRs
    queue_conditions:
      - head~=^update/
      - check-success=build-and-test
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=build-and-test
    merge_method: rebase
  - name: duplicated default from automatic merge of dependabot 🤖
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=build-and-test
      - base=main
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=build-and-test
    merge_method: rebase
