name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
#      - uses: coursier/cache-action@v6.4
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          cache: 'sbt'
          check-for-updates: true

      - name: Scalafmt check
        run: sbt scalafmtCheck

      - name: Run tests
        run: sbt test

      - name: Package artifact
        run: sbt universal:packageBin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bus-info-bot.zip
          path: target/universal/bus-info-bot.zip
          if-no-files-found: error

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: build-and-test
    name: Docker Build, Tag, Push
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Tag
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v5.5.1
        with:
          images: ghcr.io/faustin0/bus-info-bot/app # base name for tag
          tags: |
            type=ref,event=tag
            type=sha

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
